/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

// images
import image1 from "../public/assets/photo.png";
import image2 from "../public/assets/oscar.png";

// react icons
import { BsArrowRightShort } from "react-icons/bs";

const Home: NextPage = () => {
  return (
    <div className="w-screen h-screen bg-black py-10 px-20 flex flex-col lg:flex-row gap-10 items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* --------------------------------- GREEN CARD -------------------------------------------- */}
      <div
        className={`${styles.folder} ${styles.green_folder} flex items-end relative bg-emerald-500 w-full lg:w-3/4 h-[90%]`}
      >
        <img
          className="blur-sm sm:blur-0 lg:w-[300px] lg:h-[450px] w-[170px] h-[250px] z-0 absolute bottom-0 left-1/2 -translate-x-1/2 "
          src={image1.src}
          alt=""
        />
        <div className="hover:rotate-180 transition-all absolute top-5 left-5 grid grid-cols-2 gap-1 rotate-45 ">
          <span className="w-2 h-2 bg-black rounded-full  " />
          <span className="w-2 h-2 bg-black rounded-full  " />
          <span className="w-2 h-2 bg-black rounded-full  " />
          <span className="w-2 h-2 bg-black rounded-full  " />
        </div>

        <div className=" w-full flex flex-col sm:flex-row gap-10 justify-between items-center px-10 py-10">
          <h4 className="w-32 font-semibold leading-4 text-center sm:text-left drop-shadow ">
            Because your business needs a lot more
          </h4>
          <button className="transition-all hover:bg-slate-100 hover:shadow-xl hover:border-slate-100 border z-50 border-zinc-900 rounded-3xl flex items-center justify-between gap-2 sm:gap-10 px-5 py-3 ">
            <span className="text-xs drop-shadow">Get expert advise</span>
            <span className="bg-black rounded-full w-5 h-5 flex items-center justify-center">
              <BsArrowRightShort className="text-white" />
            </span>
          </button>
        </div>
      </div>

      {/* --------------------------------- GOLD CARD -------------------------------------------- */}
      <div
        className={`${styles.folder} ${styles.gold_folder} bg-amber-400  w-full lg:w-1/4 h-[90%]`}
      >
        <img
          className="w-[60px] h-[200px]  blur-sm sm:blur-0 drop-shadow absolute bottom-1/2 translate-y-1/2 left-1/2 -translate-x-1/2 "
          src={image2.src}
          alt=""
        />

        <div className="flex flex-col sm:flex-row lg:flex-col justify-between items-center h-full px-10 text-center py-10 ">
          <div className="flex flex-col gap-2 drop-shadow">
            <h2 className="italic text-3xl ">the</h2>
            <h1 className="italic text-4xl font-semibold ">OSCAR</h1>
          </div>
          <p className="text-center w-full  sm:w-1/3 lg:w-2/3 drop-shadow leading-5  lg:translate-x-0 ">
            Get your family an
            <span className="font-semibold block">OSCAR</span> this year !
          </p>
        </div>
      </div>
    </div>
  );
};

export default Home;
